# Generated by Django 2.2.7 on 2019-11-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productdetails',
        ),
    ]
