# Generated by Django 2.2.7 on 2019-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
