# Generated by Django 2.2.7 on 2019-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0002_auto_20191119_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='url',
            field=models.TextField(),
        ),
    ]
