# Generated by Django 2.2.7 on 2019-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0003_auto_20191120_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
