# Generated by Django 2.2.7 on 2020-02-20 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdetail', '0004_auto_20191120_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
